# Site settings
title: A blog about our findings and musings
description: IEEE NITK is a student branch of IEEE located at NITK Surathkal. This blog serves as a collection of ideas and thoughts of different members in various technical areas.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://ieeenitk.org" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: IEEE-NITK 
user_description: IEEE Student chapter at NITK Surathkal
description: A blog documenting random findings and musings of our members
email: chairman.nitkieee@gmail.com
twitter_username: IEEE_NITK 
github_username: IEEE-NITK
facebook_username: IEEENITK

#Facebook Sharing
facebook_app_id: 0011038251882641

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /blog
  - title: Tags
    url: /blog/tags
  - title: Main Website
    url: /
  - title: Gyan
    url: /gyan

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# extra plugins
plugins_dir: 
 ['jekyll-paginate']

# Gems
plugins: [jekyll-paginate]
# gems: [jekyll-paginate, jemoji]

# Make 6 articles per page
paginate: 6
paginate_path: "/page:num/"

future: true
